name: dvl_chart
description: DVL Chart Flutter App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  fl_chart: ^0.66.0
  window_manager: ^0.3.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - logo.jpg
